import fastaParse
import nose

def setup():
    testfile = open("test.fasta", "rb")
    proteins = fastaParse.fastaParser(testfile, "fasta")
    return proteins

def test_parser():
    proteingen = setup()
    names = ["sp|P02768|ALBU_HUMAN", "sp|P01308|INS_HUMAN"]
    seqs = [("MKWVTFISLLFLFSSAYSRGVFRRDAHKSEVAHRFKDLGEENFKALVLIAFAQYLQQCPFEDH"+
             "VKLVNEVTEFAKTCVADESAENCDKSLHTLFGDKLCTVATLRETYGEMADCCAKQEPERNECF"+
             "LQHKDDNPNLPRLVRPEVDVMCTAFHDNEETFLKKYLYEIARRHPYFYAPELLFFAKRYKAAF"+
             "TECCQAADKAACLLPKLDELRDEGKASSAKQRLKCASLQKFGERAFKAWAVARLSQRFPKAEF"+
             "AEVSKLVTDLTKVHTECCHGDLLECADDRADLAKYICENQDSISSKLKECCEKPLLEKSHCIA"+
             "EVENDEMPADLPSLAADFVESKDVCKNYAEAKDVFLGMFLYEYARRHPDYSVVLLLRLAKTYE"+
             "TTLEKCCAAADPHECYAKVFDEFKPLVEEPQNLIKQNCELFEQLGEYKFQNALLVRYTKKVPQ"+
             "VSTPTLVEVSRNLGKVGSKCCKHPEAKRMPCAEDYLSVVLNQLCVLHEKTPVSDRVTKCCTES"+
             "LVNRRPCFSALEVDETYVPKEFNAETFTFHADICTLSEKERQIKKQTALVELVKHKPKATKEQ"+
             "LKAVMDDFAAFVEKCCKADDKETCFAEEGKKLVAASQAALGL"),
            ("MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRREAEDLQV"+
             "GQVELGGGPGAGSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCN")]
    counter = 0
    for prot in proteingen:
        nose.tools.eq_(prot.name, names[counter])
        nose.tools.eq_(prot.seq, seqs[counter])
        counter += 1
    return
